# These are supported funding model platforms
We can run this model into online server so that it would be easy to identify the students capacity of learning/knowledge.
A perfect book/article will be recommended to that student based on his/her capacity.
Students can be aware about their capacity ad each student can be judged equally through this system. 
In this scenario, students choices are very much higher than their capacity or knowledge. They do not know their capacity, they do not know whether they will be able
to learn that particular topic or not. So to use this system we can directly overcome this problem. A particular student will be judged very carefully 
and the article will be recommended to them as per their knowledge level. So step my step learning, growing and increasing knowledge will be helpful for the
students through this system. 
