# These are supported funding model platforms
We can run this model into online server so that it would be easy to identify the students capacity of learning/knowledge and a perfect book/article will be recommended to that student.
